### ISSUE TITLE
Concat between brackets?

### ISSUE THREAD

**Issue by thomasahle** [peterhalasz/v-rex#1]
Should [this code](https://github.com/peterhalasz/v-rex/blob/11e53cad282375f6f5b8c3f41cbffd0c40c6104f/regex.py#L37):
```
            if (c in ALPHABET and (prev in ALPHABET or prev == ")" or prev == "*")) or (
                c == "(" and prev in ALPHABET
            ):
                new_regex += "."
```
be
```
            if (c in ALPHABET or c == "(") and (prev in ALPHABET or prev == ")" or prev == "*")):
                new_regex += "."
```
since otherwise you won't add concats between the parentheses in e.g. "(a)(b)"

**Comment by peterhalasz** [comment]
Hey!

Thanks a lot for taking your time and checking my code. You're absolutely right, without your change the concatenation is missing for the `(0)(1)` case.

Would you like to put up a PR for the fix? If not I will do it :)

**Comment by peterhalasz** [comment]
I went ahead and [merged](
https://github.com/peterhalasz/v-rex/commit/7ed6cbb05f16e0d7f454d70eadd289cd444c8f84) your proposed fix, I hope that's OK.
Thank you very much for catching this
